### ISSUE TITLE
"failed to poll source" error on burndown chart when trying to refresh

### ISSUE THREAD

**Issue by derrickeason** [vanilla/vanillateamwork#13]
see attached screenshot, every time the chart tries to refresh it throws that error and doesn't seem to update. 

![screen shot 2017-06-09 at 3 50 25 pm](https://user-images.githubusercontent.com/4853032/26992376-65172c4a-4d2c-11e7-9788-c8fd1e4873df.png)

**Comment by evach-vf** [comment]
Are you still logged in the dashboard?
I believe you might have been logged out and that's the reason you're seeing this

**Comment by derrickeason** [comment]
You are right, it works as expected when i logged back in
